# Generated by Django 5.1.3 on 2024-12-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=10000)),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
