# Generated by Django 5.1.3 on 2024-12-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_alter_postmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='user_id',
        ),
    ]
