# Generated by Django 5.1.3 on 2024-12-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_remove_postmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
